title = '甘甘的相册'
theme = 'gallery'
copyright = "© Licorice"
defaultContentLanguage = "zh"
disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true
languageCode = "zh"
timeZone = "Europe/Berlin"
timeout = "120s"

[params]
  defaultTheme = "light"
