name: Build and Deploy Sigal Gallery

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install sigal from zgshen's GitHub
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/zgshen/sigal.git

      - name: Build gallery
        run: |
          sigal build

      - name: Add CNAME file
        run: echo "gallery.zguishen.com" > _build/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build