name: Hugo Deploy

on:
  push:
    branches:
      - master  # 或者您的主分支名称

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # 如果您使用了 Git 子模块
          fetch-depth: 0    # 获取所有历史记录

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true  # 如果您使用了 Hugo Extended 版本

      - name: Build
        run: |
          hugo --minify
          ls -la
          echo "debug..."
          ls -la public
          cat public/index.html || echo "index.html not found"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public